version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: server/
    command: node ./server.js
    depends_on:
      - mongo-setup
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo-setup:
    build: mongo-setup/
    command: node ./initDB.js
    depends_on:
      - mongo
    ports:
      - "8089:8089"
    links:
      - mongo
  client:
    build: client/
    command: npm run test:dev
    ports:
      - "8090:8090"
    depends_on:
      - server
