version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: server/
    command: node ./server.js
    depends_on:
      - mongo-setup
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo-setup:
    build: mongo-setup/
    command: node ./initDB.js
    depends_on:
      - mongo
    ports:
      - "8089:8089"
    links:
      - mongo
  client:
    build: client/
    command: http-server dist -p 8081
    network_mode: host
    ports:
      - "8081:8081"
    depends_on:
      - server
